---
language: python
python:
  - '2.7'
  - '3.3'
before_install:
  - pip install --upgrade pip
install:
  - pip install ansible-container[docker]
  - pip install molecule
before_script:
script:
  - molecule lint
before_cache:    # (for cleaning up cache)
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
